# Generated by Django 5.2 on 2025-06-19 20:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deck",
            unique_together={("card_type", "name", "owner")},
        ),
    ]
