# Generated by Django 5.2 on 2025-06-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0002_alter_deck_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="difficulty",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="card",
            name="problem",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
