# Generated by Django 5.2 on 2025-05-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_usercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='last_rating',
            field=models.CharField(blank=True, choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], default=None, max_length=10, null=True),
        ),
    ]
