# Generated by Django 5.2 on 2025-06-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0003_alter_card_difficulty_alter_card_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtype",
            name="layout",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dict with 'front' and 'back' keys listing field names for card layout",
            ),
        ),
    ]
