# Generated by Django 5.2 on 2025-05-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_usercard_last_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
