# Generated by Django 5.2 on 2025-05-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_card_category_alter_card_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='hint',
            field=models.CharField(blank=True, default=''),
        ),
    ]
