# Generated by Django 5.2 on 2025-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0006_alter_card_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="shared",
            field=models.BooleanField(
                default=False, help_text="If true, this deck is visible to all users."
            ),
        ),
    ]
