# Generated by Django 5.2 on 2025-06-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0007_deck_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="usercard",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("known", "Known"), ("review", "Need Review")],
                default="new",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="last_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("again", "Again"),
                    ("hard", "Hard"),
                    ("good", "Good"),
                    ("easy", "Easy"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
