# Generated by Django 5.2 on 2025-06-16 22:04

from django.db import migrations

def forwards(apps, schema_editor):
    Card     = apps.get_model("flashcards", "Card")
    CardType = apps.get_model("flashcards", "CardType")
    # 1) get or create a “Default” type
    default_type, _ = CardType.objects.get_or_create(
        name="Default",
        defaults={
            "owner_id": 1,
            "fields": [
                "problem",
                "difficulty",
                "category",
                "hint",
                "pseudo",
                "solution",
                "complexity",
                "tags",
            ],
        }
    )
    # 2) loop and backfill
    for card in Card.objects.all():
        # copy old fields into JSON
        card.data = {
            "problem":    card.problem,
            "difficulty": card.difficulty,
            "category": card.category,
            "hint":       card.hint,
            "pseudo":     card.pseudo,
            "solution":   card.solution,
            "complexity": card.complexity,
            "tags":       card.tags,
        }
        card.card_type_id = default_type.pk
        card.save(update_fields=["data", "card_type_id"])

class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_add_cardtype_fields_as_json'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
