# Generated by Django 5.2 on 2025-06-16 23:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_card_data_cardtype_card_card_type_chatgptrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='fields',
            field=models.JSONField(blank=True, default=list, help_text='List of JSON keys that each Card.data must include'),
        ),
    ]
