# Generated by Django 5.2 on 2025-06-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_auto_20250616_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptrequest',
            name='card_type',
            field=models.ForeignKey(blank=True, help_text='Which CardType this request was targeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_requests', to='flashcards.cardtype'),
        ),
        migrations.AddField(
            model_name='deck',
            name='card_type',
            field=models.ForeignKey(blank=True, help_text='What type of cards this deck contains', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decks', to='flashcards.cardtype'),
        ),
        migrations.AlterField(
            model_name='card',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='A dict whose keys must come from card_type.fields'),
        ),
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together={('card_type', 'name')},
        ),
    ]
