# Generated by Django 5.2 on 2025-06-17 19:21

from django.db import migrations

def forwards(apps, schema_editor):
    Deck     = apps.get_model("flashcards", "Deck")
    CardType = apps.get_model("flashcards", "CardType")

    # 1) create or get the Algorithm type
    algorithm, _ = CardType.objects.get_or_create(
        name="Algorithm",
        defaults={
            "owner_id": 1,
            "fields": [
                "problem",
                "difficulty",
                "category",
                "hint",
                "pseudo",
                "solution",
                "complexity",
                "tags",
            ],
        }
    )

    # 2) assign it to every deck that’s currently null
    Deck.objects.filter(card_type__isnull=True).update(card_type=algorithm)

class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_chatgptrequest_card_type_deck_card_type_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
