# Generated by Django 5.2 on 2025-06-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_auto_20250617_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='card_type',
            field=models.ForeignKey(help_text='What type of cards this deck contains', on_delete=django.db.models.deletion.PROTECT, related_name='decks', to='flashcards.cardtype'),
        ),
    ]
