# Generated by Django 5.2 on 2025-06-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0013_alter_deck_card_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
