version: '3.9'
services:
  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: flashuser
      POSTGRES_PASSWORD: flashpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build: ./frontend/algo-flashcards
    command: npm run preview
    working_dir: /app
    volumes:
      - ./frontend/algo-flashcards:/app
    env_file:
      - ./frontend/algo-flashcards/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  pgdata:
