version: '3.9'
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend/algo-flashcards
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend/algo-flashcards:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend
